# -----------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright © 2024 bomctl a Series of LF Projects, LLC
# SPDX-FileName: action.yml
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0
# -----------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------
---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: bomctl-action
author: bomctl
description: Installs bomctl and includes it in your path

branding:
  icon: database
  color: blue

inputs:
  version:
    description: The version of bomctl to use. Can be a tagged release, commit SHA, branch name, or "latest"
    default: latest
    required: false
  install-dir:
    description: Path of bomctl install directory (will be created if it doesn't exist)
    required: false

outputs:
  bomctl-binary:
    description: Path to installed bomctl binary
    value: ${{ steps.install.outputs.bomctl-binary }}
  bomctl-version:
    description: Version of installed bomctl binary
    value: ${{ steps.install.outputs.bomctl-version }}

runs:
  using: composite
  steps:
    - name: Install bomctl
      id: install
      shell: bash
      run: .github/scripts/install.sh
