# -----------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright © 2024 bomctl a Series of LF Projects, LLC
# SPDX-FileName: .github/workflows/test-action.yml
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0
# -----------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------

---
name: test-bomctl-action

on:
  push: # For testing, remove before merge
    branches: "*"

  pull_request:
    branches: main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  test-install:
    name: Install bomctl and test presence in path
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install bomctl
        id: install
        uses: ./

      - name: Verify installed binary exists and is executable
        shell: bash
        run: test -x ${{ steps.install.outputs.bomctl-binary }}

      - name: Verify install found in PATH
        shell: bash
        run: echo -n "command -v bomctl ==> " && command -v bomctl &&
          test $(command -v bomctl) == ${{ steps.install.outputs.bomctl-binary }}

      - name: Verify version subcommand
        shell: bash
        run: bomctl version
